"""empty message

Revision ID: 1d256c0e70c
Revises: 41f9f1a2237
Create Date: 2015-10-13 19:50:14.664686

"""

# revision identifiers, used by Alembic.
revision = '1d256c0e70c'
down_revision = '41f9f1a2237'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('confirmed', sa.Boolean(), nullable=True))
    op.drop_column('users', 'comfirmed')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('comfirmed', sa.BOOLEAN(), nullable=True))
    op.drop_column('users', 'confirmed')
    ### end Alembic commands ###
