"""empty message

Revision ID: 39d2232ca1e
Revises: 49572df4375
Create Date: 2015-10-24 10:11:18.460050

"""

# revision identifiers, used by Alembic.
revision = '39d2232ca1e'
down_revision = '49572df4375'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('body_html', sa.Text(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('posts', 'body_html')
    ### end Alembic commands ###
