"""添加确认账户

Revision ID: 41f9f1a2237
Revises: None
Create Date: 2015-10-13 12:11:59.918741

"""

# revision identifiers, used by Alembic.
revision = '41f9f1a2237'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('comfirmed', sa.Boolean(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'comfirmed')
    ### end Alembic commands ###
