"""empty message

Revision ID: cc846b6f4e
Revises: 48e9d87315c
Create Date: 2015-10-23 10:27:47.172364

"""

# revision identifiers, used by Alembic.
revision = 'cc846b6f4e'
down_revision = '48e9d87315c'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('avatar_hash', sa.String(length=32), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'avatar_hash')
    ### end Alembic commands ###
